# Generated by Django 5.2.8 on 2025-12-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_category_tag_taggroup_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_options',
            field=models.JSONField(blank=True, default=list, help_text='مثال: [{"label": "۵۰ میل", "value": 50, "price": 3200000, "stock": 15}, ...]'),
        ),
    ]
