# Generated by Django 5.2.8 on 2025-12-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='از این تعداد به بالا')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='تا این تعداد (خالی = بدون سقف)', null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=0, help_text='قیمت هر عدد در این بازه (تومان)', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='products.product')),
            ],
            options={
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
