# Generated by Django 5.2.8 on 2025-12-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_pricingrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_color',
            field=models.CharField(default='primary', help_text='رنگ برچسب در فرانت', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, help_text="متن برچسب مثل 'جدید' یا 'پرفروش'", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='موجودی انبار'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='درصد تخفیف (0-100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='قیمت اصلی (قبل از تخفیف)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='perfume_type',
            field=models.CharField(blank=True, help_text='نوع عطر: EDP, EDT, ...', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='seasons',
            field=models.JSONField(blank=True, default=list, help_text='["spring", "summer", ...]'),
        ),
        migrations.AddField(
            model_name='product',
            name='similar_perfume',
            field=models.CharField(blank=True, help_text='نام عطر مشابه (مثلاً Bleu de Chanel)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0, help_text='تعداد فروش رفته'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, help_text='مثلاً 100ml', max_length=20),
        ),
    ]
