# Generated by Django 5.2.8 on 2025-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام بنر برای شناسایی (مثلاً: فروش تابستان)', max_length=200)),
                ('image', models.ImageField(help_text='اندازه پیشنهادی: 1920x600', upload_to='banners/')),
                ('link', models.CharField(blank=True, help_text='لینک اختیاری (مثلاً /products/sale)', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش (کمتر = بالاتر)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['order', 'id'],
            },
        ),
    ]
